name = "peering"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "c7c15d640c62b31052dfe8ffaf22aa66"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket="./public"
entry-point="./"
